[package]
name = "rcc4"
version = "0.1.0"
authors = ["Shingo Kato <katomail0510@gmail.com>"]
edition = "2018"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm10-0" }
